### ISSUE TITLE
Check that domains are not owned by more than one participant

### ISSUE THREAD

**Issue by jagland** [ukf/ukf-members#4]
It is possible currently for a domain verification to exist against more than one member, this might occur when a domain transfers from one member to another.    A domain can only ever have one Registrant (we use Grants when permission of an organisation has been granted by the owner)

We can get a basic heads-up by running this shell command against members.xml 
`grep -i Domain members.xml | awk -F\> '{ print $2}' | awk -F\< '{print $1}' | sort  | grep -v '^$' | uniq -c | grep -v ' 1 '`

This tooling should check for this situation - please :)

**Comment by iay** [comment]
Relatively easy one to do while building the members bean.
